---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  Minimal AWS permissions required to deploy Webiny.

##############################
#
# Parameters
#
##############################

# Parameters:


##############################
#
# Resources
#
##############################

Resources:

  WebinyDeploymentPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: Webiny-deployment-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
            - apigateway:DELETE
            - apigateway:GET
            - apigateway:POST
            - apigateway:PUT
            - cloudfront:CreateDistribution
            - cloudfront:DeleteDistribution
            - cloudfront:GetDistributionConfig
            - cloudfront:UpdateDistribution
            - cognito-idp:CreateUserPool
            - cognito-idp:CreateUserPoolClient
            - cognito-idp:DeleteUserPool
            - iam:AttachRolePolicy
            - iam:CreateRole
            - iam:DeleteRole
            - iam:DetachRolePolicy
            - iam:GetRole
            - iam:PassRole
            - kms:CreateGrant
            - kms:Decrypt
            - kms:DescribeKey
            - kms:Encrypt
            - lambda:AddPermission
            - lambda:CreateFunction
            - lambda:CreateFunction20150331
            - lambda:DeleteFunction
            - lambda:DeleteFunction20150331
            - lambda:GetFunctionConfiguration
            - lambda:GetFunctionConfiguration20150331v2
            - lambda:UpdateFunctionCode
            - lambda:UpdateFunctionConfiguration
            - s3:CreateBucket
            - s3:ListBucket
            - s3:PutAccelerateConfiguration
            - s3:PutBucketCORS
            - s3:PutBucketNotification
            - s3:PutObject
            Resource: "*"
            Effect: Allow
      Users:
        - !Ref WebinyDeploymentUser
      # Roles:
      #   - !Ref WebinyDeploymentRole

  WebinyDeploymentUser:
    Type: AWS::IAM::User
    Properties:
      UserName: Webiny-deployment-user

  WebinyUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref WebinyDeploymentUser

  # WebinyDeploymentRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     RoleName: Webiny-deployment-role
  #     Description: Role that have to be used when deploying Webiny on AWS.
  #     AssumeRolePolicyDocument:
  #       Version: 2012-10-17
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             AWS:
  #             - !Sub "arn:aws:iam::${AWS::AccountId}:root"
  #           Action:
  #             - 'sts:AssumeRole'


##############################
#
# Outputs
#
##############################

Outputs:
  WebinyUserName:
    Description: >
      Webiny User name.
    Value: !Ref WebinyDeploymentUser

#   WebinyUserAccessKeyId:
#     Description: >
#       Webiny User Access Key Id.
#     Value: !Ref WebinyUserAccessKey
#   WebinyUserSecretAccessKey:
#     Description: >
#       Webiny User Access Key Id.
#     Value: !GetAtt WebinyUserAccessKey.SecretAccessKey
  # WebinyDeploymentRoleArn:
  #   Description: Role arn to use when deploying webiny
  #   Value: !GetAtt WebinyDeploymentRole.Arn
