---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  AWS role with minimal permissions required to deploy Webiny.

##############################
#
# Parameters
#
##############################

# Parameters:


##############################
#
# Resources
#
##############################

Resources:

  WebinyDeploymentPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: Webiny-deployment-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
            - apigateway:*
            - cognito-idp:CreateUserPoolClient
            - iam:AttachRolePolicy
            - iam:CreateRole
            - iam:DeleteRole
            - iam:DetachRolePolicy
            - iam:GetRole
            - kms:CreateGrant
            - kms:Decrypt
            - kms:DescribeKey
            - kms:Encrypt
            - lambda:AddPermission
            - lambda:CreateFunction
            - lambda:DeleteFunction
            - lambda:GetFunctionConfiguration
            - s3:CreateBucket
            - s3:PutBucketCORS
            - s3:PutBucketNotification
            Resource: "*"
            Effect: Allow
      Users:
        - !Ref WebinyUser

  WebinyUser:
    Type: AWS::IAM::User
    Properties:
      UserName: Webiny-user
      # ManagedPolicyArns:
      #   - arn:aws:iam::aws:policy/AmazonS3FullAccess
      #   - arn:aws:iam::aws:policy/AmazonCognitoPowerUser
      #   - arn:aws:iam::aws:policy/AWSLambdaFullAccess
      #   - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
      #   - arn:aws:iam::aws:policy/CloudFrontFullAccess
      #   - arn:aws:iam::aws:policy/CloudWatchFullAccess
      #   - arn:aws:iam::aws:policy/IAMFullAccess

  WebinyUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref WebinyUser

  WebinyDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Webiny-deployment-role
      Description: Role that have to be used when deploying Webiny on AWS.
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonCognitoPowerUser
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
        - arn:aws:iam::aws:policy/CloudFrontFullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/IAMFullAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
              - !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - 'sts:AssumeRole'


##############################
#
# Outputs
#
##############################

Outputs:
  WebinyDeploymentRoleArn:
    Description: Role arn to use when deploying webiny
    Value: !GetAtt WebinyDeploymentRole.Arn
  WebinyUserAccessKeyId:
    Description: >
      Webiny User Access Key Id.
    Value: !Ref WebinyUserAccessKey
  WebinyUserSecretAccessKey:
    Description: >
      Webiny User Access Key Id.
    Value: !GetAtt WebinyUserAccessKey.SecretAccessKey
