---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  AWS user with minimal permissions required to deploy Webiny.

##############################
#
# Parameters
#
##############################

# Parameters:


##############################
#
# Resources
#
##############################

Resources:

  WebinyUser:
    Type: AWS::IAM::User
    UserName: Webiny-user
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/AmazonESCognitoAccess
      - arn:aws:iam::aws:policy/AWSLambdaFullAccess
      - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
      - arn:aws:iam::aws:policy/CloudFrontFullAccess
      - arn:aws:iam::aws:policy/CloudWatchFullAccess

    WebinyUserAccessKey:
      Type: AWS::IAM::AccessKey
      Properties:
        UserName: !Ref WebinyUser


##############################
#
# Outputs
#
##############################

Outputs:
  WebinyUserAccessKeyId:
    Description: >
      Webiny User Access Key Id.
    Value: !Ref WebinyUserAccessKey
  WebinySecretAccessKey:
    Description: >
      Webiny User Access Key Id.
    Value: !GetAtt WebinyUserAccessKey.SecretAccessKey
